### ISSUE TITLE
Conversation Summary w/ Keith (Only E Cigz Owner)

### ISSUE THREAD

**Issue by Demetrius-B** [fullsail/capstone-Demetrius-B#12]
> Keith has more to say so I'll be adding more notes when I receive them

**General Notes**
* Get's sketched out by 3rd party api's.
* An NDA is required for my safety. [Student Non-Disclosure Agreement (NDA)](https://nondisclosureagreement.com/student.html)
* **Important!**
  * Since I've already gained Keith's trust he's not skeptical towards giving me his data set. **BUT** if I didn't know him It would be difficult. 

**Questions asked by Keith (need to give him a proper response)**
* Does it cost any money?
* Are you going to leak my data to any hackers? SERIOUSLY!

**Action Items**
* [ ] Find a better way to get Business owners on board with my application.
* [ ] Review and fully understand Studnet NDA.
* [ ] Communicate with my instructor and figure out what to do about the NDA required.
* [ ] Revisit Only E Cigz to get an official outdated copy of their data set.

**Follow up**
- Might need to create a new **user story**
- **Functional requirements** may be changed

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Demetrius Berkeley | @Demetrius-B  |

**Comment by reactivepixel** [comment]
3rd party API might be a miscommunication.

Discussed with @Demetrius-B that integrating a business's data to help shape the structure of your application might be more problematic as the value of this is not seen.

Okay to close.

**Comment by Demetrius-B** [comment]
**Top 25 Vape Juices(Most Sold)**
