### ISSUE TITLE
Business Account Management

### ISSUE THREAD

**Issue by Demetrius-B** [fullsail/capstone-Demetrius-B#14]
**Related User Story** - #13 

**Functional Requirement**
-  [x] The System must be running live.
- [x] The System must authenticate users.
- [x] The System must allow auth users to make changes to their business.

**Comment by reactivepixel** [comment]
Production Server located at https://howling-asylum-38250.herokuapp.com/

**Comment by Demetrius-B** [comment]
- [ ] Add AccessToken to db
- [ ] add new route 'api/current_user/info'

**Comment by Demetrius-B** [comment]
Removed 'The System must allow auth users to make changes to their business.' because it's not needed and this isn't a social app.

**Comment by Demetrius-B** [comment]
**For Public Release**
- [ ] Add Forgot password

**Comment by Demetrius-B** [comment]
Changed Issue name from **Business Account Management** to **Live Server Authentication**. The issue name did not fit the description.

**Comment by reactivepixel** [comment]
Adding back in:
- [ ] The System must allow auth users to make changes to their business.

Ideally the business should be able to fill out their profile and detail how their business will display within the flavor chaser system.
