### ISSUE TITLE
Only Vape Juice Inventory Import

### ISSUE THREAD

**Issue by Demetrius-B** [fullsail/capstone-Demetrius-B#18]
**Related User Story** - #17 

**Functional Requirement**
- The system must set the data map based on user input conditional.

**Comment by Demetrius-B** [comment]
Created new Branch vape-juice-inventory-import

**Comment by Demetrius-B** [comment]
- [x] Create import & Export Buttons
- [ ] Pull Data from Square API
- [ ] Save data to a local database
- [ ] Match dataset with incoming data set?
- [ ] Send Data to '/inventory' route
- [ ] Display Data

**Comment by Demetrius-B** [comment]
- [ ] Create Vape Juice Model MYSQL

**Comment by reactivepixel** [comment]
Went through model associations and how to utilize. Apply this functionality to this issue.

**Comment by Demetrius-B** [comment]
- [ ] Wipe product id on import
