### ISSUE TITLE
Alpha Deadline Feedback

### ISSUE THREAD

**Issue by reactivepixel** [fullsail/capstone-Demetrius-B#24]
**General Notes**
* Shown code working building and running on the staging server.
* Production server configured on Heroku, but not Staging.
    * No PRs to the release branch yet.
* Technical Debt: Better to configure servers when there is minimal source code to support. 
* Readme need to be configured to present the required information sections.
* Went through the workflow for creating a business info route. (see pics from whiteboard below)
* Documentation for each route of the API you are building is required.
* Consider removing the duplicate logic of removing the keys files and just use env vars. 

**Action Items**
* [ ] maxAge should be converted into maxDays and max age should be the millisecond conversion of that variable.
* [x] Release Alpha PR to Master
* [x] Staging Server Configured and Alpha Codebase Deployed
* [x] Production Alpha Codebase Deployed
* [x] Transcribe whiteboarded workflow into 

**Follow up**
When the Alpha release is ready, message @reactivepixel.

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Chapman | @reactivepixel |
| Demetrius | @Demetrius-B  |

![img](https://i.imgur.com/CUDzqxy.jpg)
![img](https://i.imgur.com/MeNEcWu.jpg)

**Comment by Demetrius-B** [comment]
Staging Server - https://howling-asylum-38250.herokuapp.com/

**Comment by Demetrius-B** [comment]
Staging Server - https://howling-asylum-38250.herokuapp.com/
