### ISSUE TITLE
Square Data Feedback

### ISSUE THREAD

**Issue by reactivepixel** [fullsail/capstone-Demetrius-B#3]
**General Notes**
* Your testing data on square should have at least 10 entries to allow proper testing with.
* Multiple locations may cause problems. Careful. One owner can exist for two separate stores and you will need to show inventory at both locations.
* Reach out to vape shop owner to get an export of data.
* Discuss AWS EC2 server, Digital Ocean for getting a full virtual private server up and configured and settled on exclusively using Heroku.

**Action Items**
* [x] Create at least 10 testing items in the square account.
* [x] Move User Stories and Functional Requirements from approved docs to actual GitHub issues (correctly labeled)

**Follow up**
End of day (5pm) today (Monday - Week 2)

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Chapman | @reactivepixel |
| Demetrius | @Demetrius-B  |

**Comment by Demetrius-B** [comment]
Testing Items:
![testing-items](https://i.imgur.com/undefined.png)

**Comment by Demetrius-B** [comment]
User Stories and Functional Requirements have been made into issues.
