### ISSUE TITLE
Lecture #10

### ISSUE THREAD

**Issue by reactivepixel** [fullsail/capstone-Demetrius-B#33]
> **Label**: Should be labeled as `feedback`

**General Notes**

Discussed current time /difficulty breakdown of the state of the project.
*(25) 45% -Data Map
    * Data Map Conditional (only Vape Juice)
    * Save Data From Import
    * Create Map of Data Conversion
    * Create Interface to allow Map
* (0) 10% - Notifications
    * Subscription when restock
    * Following
* (90 13d to 100) 5% - System is Accessible
    * Routes
    * Business Profiles
* (0) 15% - Search
    * Location
    * product type
    * Other filters ?
* (0) 25% - User Side
    * Build User Side App using your API

Current Rate of progression@ 13d = 5%
100% = 260d 14d 

An increase of a factor 18.6x to hit 14d deadline is unattainable. DO NOT /can not work 56h per day to hit project goal. We discussed sharply refactoring schedule and priorities to be more efficient with time available.

**Action Items**
* [x] List of brainstormed efficeny ideas
* [x] List of applied efficeny ideas

**Follow up**
Friday review both lists.

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Chapman | @reactivepixel |
| Demetrius | @demetrius |

**Comment by Demetrius-B** [comment]
I addressed this issue on Friday. You never responded to go over the list with me.

**Comment by Demetrius-B** [comment]
Closing this issue the instructor never followed up.
